/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedFormadorRouteImport } from './routes/_authenticated/formador'
import { Route as Mf1IndexRouteImport } from './routes/mf1.index'
import { Route as Mf1AuthRouteImport } from './routes/mf1.auth'
import { Route as Mf1FontesRouteImport } from './routes/mf1.fontes'
import { Route as Mf2IndexRouteImport } from './routes/mf2.index'
import { Route as Mf2FontesRouteImport } from './routes/mf2.fontes'
import { Route as Mf3IndexRouteImport } from './routes/mf3.index'
import { Route as Mf3FontesRouteImport } from './routes/mf3.fontes'
import { Route as AuthenticatedMf1SinteseRouteImport } from './routes/_authenticated/mf1.sintese'
import { Route as AuthenticatedMf2SinteseRouteImport } from './routes/_authenticated/mf2.sintese'
import { Route as AuthenticatedMf3SinteseRouteImport } from './routes/_authenticated/mf3.sintese'
import { Route as AuthenticatedMf1AtividadesIndexRouteImport } from './routes/_authenticated/mf1.atividades.index'
import { Route as AuthenticatedMf1AtividadesAtividadeIdRouteImport } from './routes/_authenticated/mf1.atividades.$atividadeId'
import { Route as AuthenticatedMf1BlocosBlocoIdRouteImport } from './routes/_authenticated/mf1.blocos.$blocoId'
import { Route as AuthenticatedMf2AtividadesIndexRouteImport } from './routes/_authenticated/mf2.atividades.index'
import { Route as AuthenticatedMf2AtividadesAtividadeIdRouteImport } from './routes/_authenticated/mf2.atividades.$atividadeId'
import { Route as AuthenticatedMf2BlocosBlocoIdRouteImport } from './routes/_authenticated/mf2.blocos.$blocoId'
import { Route as AuthenticatedMf3AtividadesIndexRouteImport } from './routes/_authenticated/mf3.atividades.index'
import { Route as AuthenticatedMf3AtividadesAtividadeIdRouteImport } from './routes/_authenticated/mf3.atividades.$atividadeId'
import { Route as AuthenticatedMf3BlocosBlocoIdRouteImport } from './routes/_authenticated/mf3.blocos.$blocoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFormadorRoute = AuthenticatedFormadorRouteImport.update({
  id: '/formador',
  path: '/formador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Mf1IndexRoute = Mf1IndexRouteImport.update({
  id: '/mf1/',
  path: '/mf1/',
  getParentRoute: () => rootRouteImport,
} as any)
const Mf1AuthRoute = Mf1AuthRouteImport.update({
  id: '/mf1/auth',
  path: '/mf1/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const Mf1FontesRoute = Mf1FontesRouteImport.update({
  id: '/mf1/fontes',
  path: '/mf1/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const Mf2IndexRoute = Mf2IndexRouteImport.update({
  id: '/mf2/',
  path: '/mf2/',
  getParentRoute: () => rootRouteImport,
} as any)
const Mf2FontesRoute = Mf2FontesRouteImport.update({
  id: '/mf2/fontes',
  path: '/mf2/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const Mf3IndexRoute = Mf3IndexRouteImport.update({
  id: '/mf3/',
  path: '/mf3/',
  getParentRoute: () => rootRouteImport,
} as any)
const Mf3FontesRoute = Mf3FontesRouteImport.update({
  id: '/mf3/fontes',
  path: '/mf3/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMf1SinteseRoute = AuthenticatedMf1SinteseRouteImport.update({
  id: '/mf1/sintese',
  path: '/mf1/sintese',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMf2SinteseRoute = AuthenticatedMf2SinteseRouteImport.update({
  id: '/mf2/sintese',
  path: '/mf2/sintese',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMf3SinteseRoute = AuthenticatedMf3SinteseRouteImport.update({
  id: '/mf3/sintese',
  path: '/mf3/sintese',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMf1AtividadesIndexRoute =
  AuthenticatedMf1AtividadesIndexRouteImport.update({
    id: '/mf1/atividades/',
    path: '/mf1/atividades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMf1AtividadesAtividadeIdRoute =
  AuthenticatedMf1AtividadesAtividadeIdRouteImport.update({
    id: '/mf1/atividades/$atividadeId',
    path: '/mf1/atividades/$atividadeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMf1BlocosBlocoIdRoute =
  AuthenticatedMf1BlocosBlocoIdRouteImport.update({
    id: '/mf1/blocos/$blocoId',
    path: '/mf1/blocos/$blocoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMf2AtividadesIndexRoute =
  AuthenticatedMf2AtividadesIndexRouteImport.update({
    id: '/mf2/atividades/',
    path: '/mf2/atividades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMf2AtividadesAtividadeIdRoute =
  AuthenticatedMf2AtividadesAtividadeIdRouteImport.update({
    id: '/mf2/atividades/$atividadeId',
    path: '/mf2/atividades/$atividadeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMf2BlocosBlocoIdRoute =
  AuthenticatedMf2BlocosBlocoIdRouteImport.update({
    id: '/mf2/blocos/$blocoId',
    path: '/mf2/blocos/$blocoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMf3AtividadesIndexRoute =
  AuthenticatedMf3AtividadesIndexRouteImport.update({
    id: '/mf3/atividades/',
    path: '/mf3/atividades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMf3AtividadesAtividadeIdRoute =
  AuthenticatedMf3AtividadesAtividadeIdRouteImport.update({
    id: '/mf3/atividades/$atividadeId',
    path: '/mf3/atividades/$atividadeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMf3BlocosBlocoIdRoute =
  AuthenticatedMf3BlocosBlocoIdRouteImport.update({
    id: '/mf3/blocos/$blocoId',
    path: '/mf3/blocos/$blocoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/formador': typeof AuthenticatedFormadorRoute
  '/mf1/auth': typeof Mf1AuthRoute
  '/mf1/fontes': typeof Mf1FontesRoute
  '/mf2/fontes': typeof Mf2FontesRoute
  '/mf3/fontes': typeof Mf3FontesRoute
  '/mf1/': typeof Mf1IndexRoute
  '/mf2/': typeof Mf2IndexRoute
  '/mf3/': typeof Mf3IndexRoute
  '/mf1/sintese': typeof AuthenticatedMf1SinteseRoute
  '/mf2/sintese': typeof AuthenticatedMf2SinteseRoute
  '/mf3/sintese': typeof AuthenticatedMf3SinteseRoute
  '/mf1/atividades/$atividadeId': typeof AuthenticatedMf1AtividadesAtividadeIdRoute
  '/mf1/blocos/$blocoId': typeof AuthenticatedMf1BlocosBlocoIdRoute
  '/mf2/atividades/$atividadeId': typeof AuthenticatedMf2AtividadesAtividadeIdRoute
  '/mf2/blocos/$blocoId': typeof AuthenticatedMf2BlocosBlocoIdRoute
  '/mf3/atividades/$atividadeId': typeof AuthenticatedMf3AtividadesAtividadeIdRoute
  '/mf3/blocos/$blocoId': typeof AuthenticatedMf3BlocosBlocoIdRoute
  '/mf1/atividades/': typeof AuthenticatedMf1AtividadesIndexRoute
  '/mf2/atividades/': typeof AuthenticatedMf2AtividadesIndexRoute
  '/mf3/atividades/': typeof AuthenticatedMf3AtividadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/formador': typeof AuthenticatedFormadorRoute
  '/mf1/auth': typeof Mf1AuthRoute
  '/mf1/fontes': typeof Mf1FontesRoute
  '/mf2/fontes': typeof Mf2FontesRoute
  '/mf3/fontes': typeof Mf3FontesRoute
  '/mf1': typeof Mf1IndexRoute
  '/mf2': typeof Mf2IndexRoute
  '/mf3': typeof Mf3IndexRoute
  '/mf1/sintese': typeof AuthenticatedMf1SinteseRoute
  '/mf2/sintese': typeof AuthenticatedMf2SinteseRoute
  '/mf3/sintese': typeof AuthenticatedMf3SinteseRoute
  '/mf1/atividades/$atividadeId': typeof AuthenticatedMf1AtividadesAtividadeIdRoute
  '/mf1/blocos/$blocoId': typeof AuthenticatedMf1BlocosBlocoIdRoute
  '/mf2/atividades/$atividadeId': typeof AuthenticatedMf2AtividadesAtividadeIdRoute
  '/mf2/blocos/$blocoId': typeof AuthenticatedMf2BlocosBlocoIdRoute
  '/mf3/atividades/$atividadeId': typeof AuthenticatedMf3AtividadesAtividadeIdRoute
  '/mf3/blocos/$blocoId': typeof AuthenticatedMf3BlocosBlocoIdRoute
  '/mf1/atividades': typeof AuthenticatedMf1AtividadesIndexRoute
  '/mf2/atividades': typeof AuthenticatedMf2AtividadesIndexRoute
  '/mf3/atividades': typeof AuthenticatedMf3AtividadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/formador': typeof AuthenticatedFormadorRoute
  '/mf1/auth': typeof Mf1AuthRoute
  '/mf1/fontes': typeof Mf1FontesRoute
  '/mf2/fontes': typeof Mf2FontesRoute
  '/mf3/fontes': typeof Mf3FontesRoute
  '/mf1/': typeof Mf1IndexRoute
  '/mf2/': typeof Mf2IndexRoute
  '/mf3/': typeof Mf3IndexRoute
  '/_authenticated/mf1/sintese': typeof AuthenticatedMf1SinteseRoute
  '/_authenticated/mf2/sintese': typeof AuthenticatedMf2SinteseRoute
  '/_authenticated/mf3/sintese': typeof AuthenticatedMf3SinteseRoute
  '/_authenticated/mf1/atividades/$atividadeId': typeof AuthenticatedMf1AtividadesAtividadeIdRoute
  '/_authenticated/mf1/blocos/$blocoId': typeof AuthenticatedMf1BlocosBlocoIdRoute
  '/_authenticated/mf2/atividades/$atividadeId': typeof AuthenticatedMf2AtividadesAtividadeIdRoute
  '/_authenticated/mf2/blocos/$blocoId': typeof AuthenticatedMf2BlocosBlocoIdRoute
  '/_authenticated/mf3/atividades/$atividadeId': typeof AuthenticatedMf3AtividadesAtividadeIdRoute
  '/_authenticated/mf3/blocos/$blocoId': typeof AuthenticatedMf3BlocosBlocoIdRoute
  '/_authenticated/mf1/atividades/': typeof AuthenticatedMf1AtividadesIndexRoute
  '/_authenticated/mf2/atividades/': typeof AuthenticatedMf2AtividadesIndexRoute
  '/_authenticated/mf3/atividades/': typeof AuthenticatedMf3AtividadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/formador'
    | '/mf1/auth'
    | '/mf1/fontes'
    | '/mf2/fontes'
    | '/mf3/fontes'
    | '/mf1/'
    | '/mf2/'
    | '/mf3/'
    | '/mf1/sintese'
    | '/mf2/sintese'
    | '/mf3/sintese'
    | '/mf1/atividades/$atividadeId'
    | '/mf1/blocos/$blocoId'
    | '/mf2/atividades/$atividadeId'
    | '/mf2/blocos/$blocoId'
    | '/mf3/atividades/$atividadeId'
    | '/mf3/blocos/$blocoId'
    | '/mf1/atividades/'
    | '/mf2/atividades/'
    | '/mf3/atividades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/formador'
    | '/mf1/auth'
    | '/mf1/fontes'
    | '/mf2/fontes'
    | '/mf3/fontes'
    | '/mf1'
    | '/mf2'
    | '/mf3'
    | '/mf1/sintese'
    | '/mf2/sintese'
    | '/mf3/sintese'
    | '/mf1/atividades/$atividadeId'
    | '/mf1/blocos/$blocoId'
    | '/mf2/atividades/$atividadeId'
    | '/mf2/blocos/$blocoId'
    | '/mf3/atividades/$atividadeId'
    | '/mf3/blocos/$blocoId'
    | '/mf1/atividades'
    | '/mf2/atividades'
    | '/mf3/atividades'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/mcp'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/formador'
    | '/mf1/auth'
    | '/mf1/fontes'
    | '/mf2/fontes'
    | '/mf3/fontes'
    | '/mf1/'
    | '/mf2/'
    | '/mf3/'
    | '/_authenticated/mf1/sintese'
    | '/_authenticated/mf2/sintese'
    | '/_authenticated/mf3/sintese'
    | '/_authenticated/mf1/atividades/$atividadeId'
    | '/_authenticated/mf1/blocos/$blocoId'
    | '/_authenticated/mf2/atividades/$atividadeId'
    | '/_authenticated/mf2/blocos/$blocoId'
    | '/_authenticated/mf3/atividades/$atividadeId'
    | '/_authenticated/mf3/blocos/$blocoId'
    | '/_authenticated/mf1/atividades/'
    | '/_authenticated/mf2/atividades/'
    | '/_authenticated/mf3/atividades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Mf1AuthRoute: typeof Mf1AuthRoute
  Mf1FontesRoute: typeof Mf1FontesRoute
  Mf2FontesRoute: typeof Mf2FontesRoute
  Mf3FontesRoute: typeof Mf3FontesRoute
  Mf1IndexRoute: typeof Mf1IndexRoute
  Mf2IndexRoute: typeof Mf2IndexRoute
  Mf3IndexRoute: typeof Mf3IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/formador': {
      id: '/_authenticated/formador'
      path: '/formador'
      fullPath: '/formador'
      preLoaderRoute: typeof AuthenticatedFormadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/mf1/': {
      id: '/mf1/'
      path: '/mf1'
      fullPath: '/mf1/'
      preLoaderRoute: typeof Mf1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mf1/auth': {
      id: '/mf1/auth'
      path: '/mf1/auth'
      fullPath: '/mf1/auth'
      preLoaderRoute: typeof Mf1AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mf1/fontes': {
      id: '/mf1/fontes'
      path: '/mf1/fontes'
      fullPath: '/mf1/fontes'
      preLoaderRoute: typeof Mf1FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mf2/': {
      id: '/mf2/'
      path: '/mf2'
      fullPath: '/mf2/'
      preLoaderRoute: typeof Mf2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mf2/fontes': {
      id: '/mf2/fontes'
      path: '/mf2/fontes'
      fullPath: '/mf2/fontes'
      preLoaderRoute: typeof Mf2FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mf3/': {
      id: '/mf3/'
      path: '/mf3'
      fullPath: '/mf3/'
      preLoaderRoute: typeof Mf3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mf3/fontes': {
      id: '/mf3/fontes'
      path: '/mf3/fontes'
      fullPath: '/mf3/fontes'
      preLoaderRoute: typeof Mf3FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mf1/sintese': {
      id: '/_authenticated/mf1/sintese'
      path: '/mf1/sintese'
      fullPath: '/mf1/sintese'
      preLoaderRoute: typeof AuthenticatedMf1SinteseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf2/sintese': {
      id: '/_authenticated/mf2/sintese'
      path: '/mf2/sintese'
      fullPath: '/mf2/sintese'
      preLoaderRoute: typeof AuthenticatedMf2SinteseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf3/sintese': {
      id: '/_authenticated/mf3/sintese'
      path: '/mf3/sintese'
      fullPath: '/mf3/sintese'
      preLoaderRoute: typeof AuthenticatedMf3SinteseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf1/atividades/': {
      id: '/_authenticated/mf1/atividades/'
      path: '/mf1/atividades'
      fullPath: '/mf1/atividades/'
      preLoaderRoute: typeof AuthenticatedMf1AtividadesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf1/atividades/$atividadeId': {
      id: '/_authenticated/mf1/atividades/$atividadeId'
      path: '/mf1/atividades/$atividadeId'
      fullPath: '/mf1/atividades/$atividadeId'
      preLoaderRoute: typeof AuthenticatedMf1AtividadesAtividadeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf1/blocos/$blocoId': {
      id: '/_authenticated/mf1/blocos/$blocoId'
      path: '/mf1/blocos/$blocoId'
      fullPath: '/mf1/blocos/$blocoId'
      preLoaderRoute: typeof AuthenticatedMf1BlocosBlocoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf2/atividades/': {
      id: '/_authenticated/mf2/atividades/'
      path: '/mf2/atividades'
      fullPath: '/mf2/atividades/'
      preLoaderRoute: typeof AuthenticatedMf2AtividadesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf2/atividades/$atividadeId': {
      id: '/_authenticated/mf2/atividades/$atividadeId'
      path: '/mf2/atividades/$atividadeId'
      fullPath: '/mf2/atividades/$atividadeId'
      preLoaderRoute: typeof AuthenticatedMf2AtividadesAtividadeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf2/blocos/$blocoId': {
      id: '/_authenticated/mf2/blocos/$blocoId'
      path: '/mf2/blocos/$blocoId'
      fullPath: '/mf2/blocos/$blocoId'
      preLoaderRoute: typeof AuthenticatedMf2BlocosBlocoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf3/atividades/': {
      id: '/_authenticated/mf3/atividades/'
      path: '/mf3/atividades'
      fullPath: '/mf3/atividades/'
      preLoaderRoute: typeof AuthenticatedMf3AtividadesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf3/atividades/$atividadeId': {
      id: '/_authenticated/mf3/atividades/$atividadeId'
      path: '/mf3/atividades/$atividadeId'
      fullPath: '/mf3/atividades/$atividadeId'
      preLoaderRoute: typeof AuthenticatedMf3AtividadesAtividadeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf3/blocos/$blocoId': {
      id: '/_authenticated/mf3/blocos/$blocoId'
      path: '/mf3/blocos/$blocoId'
      fullPath: '/mf3/blocos/$blocoId'
      preLoaderRoute: typeof AuthenticatedMf3BlocosBlocoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFormadorRoute: typeof AuthenticatedFormadorRoute
  AuthenticatedMf1SinteseRoute: typeof AuthenticatedMf1SinteseRoute
  AuthenticatedMf2SinteseRoute: typeof AuthenticatedMf2SinteseRoute
  AuthenticatedMf3SinteseRoute: typeof AuthenticatedMf3SinteseRoute
  AuthenticatedMf1AtividadesAtividadeIdRoute: typeof AuthenticatedMf1AtividadesAtividadeIdRoute
  AuthenticatedMf1BlocosBlocoIdRoute: typeof AuthenticatedMf1BlocosBlocoIdRoute
  AuthenticatedMf2AtividadesAtividadeIdRoute: typeof AuthenticatedMf2AtividadesAtividadeIdRoute
  AuthenticatedMf2BlocosBlocoIdRoute: typeof AuthenticatedMf2BlocosBlocoIdRoute
  AuthenticatedMf3AtividadesAtividadeIdRoute: typeof AuthenticatedMf3AtividadesAtividadeIdRoute
  AuthenticatedMf3BlocosBlocoIdRoute: typeof AuthenticatedMf3BlocosBlocoIdRoute
  AuthenticatedMf1AtividadesIndexRoute: typeof AuthenticatedMf1AtividadesIndexRoute
  AuthenticatedMf2AtividadesIndexRoute: typeof AuthenticatedMf2AtividadesIndexRoute
  AuthenticatedMf3AtividadesIndexRoute: typeof AuthenticatedMf3AtividadesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFormadorRoute: AuthenticatedFormadorRoute,
  AuthenticatedMf1SinteseRoute: AuthenticatedMf1SinteseRoute,
  AuthenticatedMf2SinteseRoute: AuthenticatedMf2SinteseRoute,
  AuthenticatedMf3SinteseRoute: AuthenticatedMf3SinteseRoute,
  AuthenticatedMf1AtividadesAtividadeIdRoute:
    AuthenticatedMf1AtividadesAtividadeIdRoute,
  AuthenticatedMf1BlocosBlocoIdRoute: AuthenticatedMf1BlocosBlocoIdRoute,
  AuthenticatedMf2AtividadesAtividadeIdRoute:
    AuthenticatedMf2AtividadesAtividadeIdRoute,
  AuthenticatedMf2BlocosBlocoIdRoute: AuthenticatedMf2BlocosBlocoIdRoute,
  AuthenticatedMf3AtividadesAtividadeIdRoute:
    AuthenticatedMf3AtividadesAtividadeIdRoute,
  AuthenticatedMf3BlocosBlocoIdRoute: AuthenticatedMf3BlocosBlocoIdRoute,
  AuthenticatedMf1AtividadesIndexRoute: AuthenticatedMf1AtividadesIndexRoute,
  AuthenticatedMf2AtividadesIndexRoute: AuthenticatedMf2AtividadesIndexRoute,
  AuthenticatedMf3AtividadesIndexRoute: AuthenticatedMf3AtividadesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Mf1AuthRoute: Mf1AuthRoute,
  Mf1FontesRoute: Mf1FontesRoute,
  Mf2FontesRoute: Mf2FontesRoute,
  Mf3FontesRoute: Mf3FontesRoute,
  Mf1IndexRoute: Mf1IndexRoute,
  Mf2IndexRoute: Mf2IndexRoute,
  Mf3IndexRoute: Mf3IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
