/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TmpPreviewRouteImport } from './routes/tmp-preview'
import { Route as AuthenticatedFormadorRouteImport } from './routes/_authenticated/formador'
import { Route as AuthenticatedSinteseRouteImport } from './routes/_authenticated/sintese'
import { Route as Mf2IndexRouteImport } from './routes/mf2.index'
import { Route as Mf2FontesRouteImport } from './routes/mf2.fontes'
import { Route as AuthenticatedAtividadesIndexRouteImport } from './routes/_authenticated/atividades.index'
import { Route as AuthenticatedAtividadesAtividadeIdRouteImport } from './routes/_authenticated/atividades.$atividadeId'
import { Route as AuthenticatedBlocosBlocoIdRouteImport } from './routes/_authenticated/blocos.$blocoId'
import { Route as AuthenticatedMf2SinteseRouteImport } from './routes/_authenticated/mf2.sintese'
import { Route as AuthenticatedMf2AtividadesIndexRouteImport } from './routes/_authenticated/mf2.atividades.index'
import { Route as AuthenticatedMf2AtividadesAtividadeIdRouteImport } from './routes/_authenticated/mf2.atividades.$atividadeId'
import { Route as AuthenticatedMf2BlocosBlocoIdRouteImport } from './routes/_authenticated/mf2.blocos.$blocoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TmpPreviewRoute = TmpPreviewRouteImport.update({
  id: '/tmp-preview',
  path: '/tmp-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFormadorRoute = AuthenticatedFormadorRouteImport.update({
  id: '/formador',
  path: '/formador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSinteseRoute = AuthenticatedSinteseRouteImport.update({
  id: '/sintese',
  path: '/sintese',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Mf2IndexRoute = Mf2IndexRouteImport.update({
  id: '/mf2/',
  path: '/mf2/',
  getParentRoute: () => rootRouteImport,
} as any)
const Mf2FontesRoute = Mf2FontesRouteImport.update({
  id: '/mf2/fontes',
  path: '/mf2/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtividadesIndexRoute =
  AuthenticatedAtividadesIndexRouteImport.update({
    id: '/atividades/',
    path: '/atividades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtividadesAtividadeIdRoute =
  AuthenticatedAtividadesAtividadeIdRouteImport.update({
    id: '/atividades/$atividadeId',
    path: '/atividades/$atividadeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBlocosBlocoIdRoute =
  AuthenticatedBlocosBlocoIdRouteImport.update({
    id: '/blocos/$blocoId',
    path: '/blocos/$blocoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMf2SinteseRoute = AuthenticatedMf2SinteseRouteImport.update({
  id: '/mf2/sintese',
  path: '/mf2/sintese',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMf2AtividadesIndexRoute =
  AuthenticatedMf2AtividadesIndexRouteImport.update({
    id: '/mf2/atividades/',
    path: '/mf2/atividades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMf2AtividadesAtividadeIdRoute =
  AuthenticatedMf2AtividadesAtividadeIdRouteImport.update({
    id: '/mf2/atividades/$atividadeId',
    path: '/mf2/atividades/$atividadeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMf2BlocosBlocoIdRoute =
  AuthenticatedMf2BlocosBlocoIdRouteImport.update({
    id: '/mf2/blocos/$blocoId',
    path: '/mf2/blocos/$blocoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fontes': typeof FontesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tmp-preview': typeof TmpPreviewRoute
  '/formador': typeof AuthenticatedFormadorRoute
  '/sintese': typeof AuthenticatedSinteseRoute
  '/mf2/fontes': typeof Mf2FontesRoute
  '/mf2/': typeof Mf2IndexRoute
  '/atividades/$atividadeId': typeof AuthenticatedAtividadesAtividadeIdRoute
  '/blocos/$blocoId': typeof AuthenticatedBlocosBlocoIdRoute
  '/mf2/sintese': typeof AuthenticatedMf2SinteseRoute
  '/atividades/': typeof AuthenticatedAtividadesIndexRoute
  '/mf2/atividades/$atividadeId': typeof AuthenticatedMf2AtividadesAtividadeIdRoute
  '/mf2/blocos/$blocoId': typeof AuthenticatedMf2BlocosBlocoIdRoute
  '/mf2/atividades/': typeof AuthenticatedMf2AtividadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fontes': typeof FontesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tmp-preview': typeof TmpPreviewRoute
  '/formador': typeof AuthenticatedFormadorRoute
  '/sintese': typeof AuthenticatedSinteseRoute
  '/mf2/fontes': typeof Mf2FontesRoute
  '/mf2': typeof Mf2IndexRoute
  '/atividades/$atividadeId': typeof AuthenticatedAtividadesAtividadeIdRoute
  '/blocos/$blocoId': typeof AuthenticatedBlocosBlocoIdRoute
  '/mf2/sintese': typeof AuthenticatedMf2SinteseRoute
  '/atividades': typeof AuthenticatedAtividadesIndexRoute
  '/mf2/atividades/$atividadeId': typeof AuthenticatedMf2AtividadesAtividadeIdRoute
  '/mf2/blocos/$blocoId': typeof AuthenticatedMf2BlocosBlocoIdRoute
  '/mf2/atividades': typeof AuthenticatedMf2AtividadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/fontes': typeof FontesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tmp-preview': typeof TmpPreviewRoute
  '/_authenticated/formador': typeof AuthenticatedFormadorRoute
  '/_authenticated/sintese': typeof AuthenticatedSinteseRoute
  '/mf2/fontes': typeof Mf2FontesRoute
  '/mf2/': typeof Mf2IndexRoute
  '/_authenticated/atividades/$atividadeId': typeof AuthenticatedAtividadesAtividadeIdRoute
  '/_authenticated/blocos/$blocoId': typeof AuthenticatedBlocosBlocoIdRoute
  '/_authenticated/mf2/sintese': typeof AuthenticatedMf2SinteseRoute
  '/_authenticated/atividades/': typeof AuthenticatedAtividadesIndexRoute
  '/_authenticated/mf2/atividades/$atividadeId': typeof AuthenticatedMf2AtividadesAtividadeIdRoute
  '/_authenticated/mf2/blocos/$blocoId': typeof AuthenticatedMf2BlocosBlocoIdRoute
  '/_authenticated/mf2/atividades/': typeof AuthenticatedMf2AtividadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fontes'
    | '/reset-password'
    | '/tmp-preview'
    | '/formador'
    | '/sintese'
    | '/mf2/fontes'
    | '/mf2/'
    | '/atividades/$atividadeId'
    | '/blocos/$blocoId'
    | '/mf2/sintese'
    | '/atividades/'
    | '/mf2/atividades/$atividadeId'
    | '/mf2/blocos/$blocoId'
    | '/mf2/atividades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fontes'
    | '/reset-password'
    | '/tmp-preview'
    | '/formador'
    | '/sintese'
    | '/mf2/fontes'
    | '/mf2'
    | '/atividades/$atividadeId'
    | '/blocos/$blocoId'
    | '/mf2/sintese'
    | '/atividades'
    | '/mf2/atividades/$atividadeId'
    | '/mf2/blocos/$blocoId'
    | '/mf2/atividades'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/fontes'
    | '/reset-password'
    | '/tmp-preview'
    | '/_authenticated/formador'
    | '/_authenticated/sintese'
    | '/mf2/fontes'
    | '/mf2/'
    | '/_authenticated/atividades/$atividadeId'
    | '/_authenticated/blocos/$blocoId'
    | '/_authenticated/mf2/sintese'
    | '/_authenticated/atividades/'
    | '/_authenticated/mf2/atividades/$atividadeId'
    | '/_authenticated/mf2/blocos/$blocoId'
    | '/_authenticated/mf2/atividades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FontesRoute: typeof FontesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TmpPreviewRoute: typeof TmpPreviewRoute
  Mf2FontesRoute: typeof Mf2FontesRoute
  Mf2IndexRoute: typeof Mf2IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tmp-preview': {
      id: '/tmp-preview'
      path: '/tmp-preview'
      fullPath: '/tmp-preview'
      preLoaderRoute: typeof TmpPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/formador': {
      id: '/_authenticated/formador'
      path: '/formador'
      fullPath: '/formador'
      preLoaderRoute: typeof AuthenticatedFormadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sintese': {
      id: '/_authenticated/sintese'
      path: '/sintese'
      fullPath: '/sintese'
      preLoaderRoute: typeof AuthenticatedSinteseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/mf2/': {
      id: '/mf2/'
      path: '/mf2'
      fullPath: '/mf2/'
      preLoaderRoute: typeof Mf2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mf2/fontes': {
      id: '/mf2/fontes'
      path: '/mf2/fontes'
      fullPath: '/mf2/fontes'
      preLoaderRoute: typeof Mf2FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atividades/': {
      id: '/_authenticated/atividades/'
      path: '/atividades'
      fullPath: '/atividades/'
      preLoaderRoute: typeof AuthenticatedAtividadesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividades/$atividadeId': {
      id: '/_authenticated/atividades/$atividadeId'
      path: '/atividades/$atividadeId'
      fullPath: '/atividades/$atividadeId'
      preLoaderRoute: typeof AuthenticatedAtividadesAtividadeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blocos/$blocoId': {
      id: '/_authenticated/blocos/$blocoId'
      path: '/blocos/$blocoId'
      fullPath: '/blocos/$blocoId'
      preLoaderRoute: typeof AuthenticatedBlocosBlocoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf2/sintese': {
      id: '/_authenticated/mf2/sintese'
      path: '/mf2/sintese'
      fullPath: '/mf2/sintese'
      preLoaderRoute: typeof AuthenticatedMf2SinteseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf2/atividades/': {
      id: '/_authenticated/mf2/atividades/'
      path: '/mf2/atividades'
      fullPath: '/mf2/atividades/'
      preLoaderRoute: typeof AuthenticatedMf2AtividadesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf2/atividades/$atividadeId': {
      id: '/_authenticated/mf2/atividades/$atividadeId'
      path: '/mf2/atividades/$atividadeId'
      fullPath: '/mf2/atividades/$atividadeId'
      preLoaderRoute: typeof AuthenticatedMf2AtividadesAtividadeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mf2/blocos/$blocoId': {
      id: '/_authenticated/mf2/blocos/$blocoId'
      path: '/mf2/blocos/$blocoId'
      fullPath: '/mf2/blocos/$blocoId'
      preLoaderRoute: typeof AuthenticatedMf2BlocosBlocoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFormadorRoute: typeof AuthenticatedFormadorRoute
  AuthenticatedSinteseRoute: typeof AuthenticatedSinteseRoute
  AuthenticatedAtividadesAtividadeIdRoute: typeof AuthenticatedAtividadesAtividadeIdRoute
  AuthenticatedBlocosBlocoIdRoute: typeof AuthenticatedBlocosBlocoIdRoute
  AuthenticatedMf2SinteseRoute: typeof AuthenticatedMf2SinteseRoute
  AuthenticatedAtividadesIndexRoute: typeof AuthenticatedAtividadesIndexRoute
  AuthenticatedMf2AtividadesAtividadeIdRoute: typeof AuthenticatedMf2AtividadesAtividadeIdRoute
  AuthenticatedMf2BlocosBlocoIdRoute: typeof AuthenticatedMf2BlocosBlocoIdRoute
  AuthenticatedMf2AtividadesIndexRoute: typeof AuthenticatedMf2AtividadesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFormadorRoute: AuthenticatedFormadorRoute,
  AuthenticatedSinteseRoute: AuthenticatedSinteseRoute,
  AuthenticatedAtividadesAtividadeIdRoute:
    AuthenticatedAtividadesAtividadeIdRoute,
  AuthenticatedBlocosBlocoIdRoute: AuthenticatedBlocosBlocoIdRoute,
  AuthenticatedMf2SinteseRoute: AuthenticatedMf2SinteseRoute,
  AuthenticatedAtividadesIndexRoute: AuthenticatedAtividadesIndexRoute,
  AuthenticatedMf2AtividadesAtividadeIdRoute:
    AuthenticatedMf2AtividadesAtividadeIdRoute,
  AuthenticatedMf2BlocosBlocoIdRoute: AuthenticatedMf2BlocosBlocoIdRoute,
  AuthenticatedMf2AtividadesIndexRoute: AuthenticatedMf2AtividadesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FontesRoute: FontesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TmpPreviewRoute: TmpPreviewRoute,
  Mf2FontesRoute: Mf2FontesRoute,
  Mf2IndexRoute: Mf2IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
