/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as SinteseRouteImport } from './routes/sintese'
import { Route as AtividadesIndexRouteImport } from './routes/atividades.index'
import { Route as AtividadesAtividadeIdRouteImport } from './routes/atividades.$atividadeId'
import { Route as BlocosBlocoIdRouteImport } from './routes/blocos.$blocoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const SinteseRoute = SinteseRouteImport.update({
  id: '/sintese',
  path: '/sintese',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesIndexRoute = AtividadesIndexRouteImport.update({
  id: '/atividades/',
  path: '/atividades/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesAtividadeIdRoute = AtividadesAtividadeIdRouteImport.update({
  id: '/atividades/$atividadeId',
  path: '/atividades/$atividadeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocosBlocoIdRoute = BlocosBlocoIdRouteImport.update({
  id: '/blocos/$blocoId',
  path: '/blocos/$blocoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fontes': typeof FontesRoute
  '/sintese': typeof SinteseRoute
  '/atividades/$atividadeId': typeof AtividadesAtividadeIdRoute
  '/blocos/$blocoId': typeof BlocosBlocoIdRoute
  '/atividades/': typeof AtividadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fontes': typeof FontesRoute
  '/sintese': typeof SinteseRoute
  '/atividades/$atividadeId': typeof AtividadesAtividadeIdRoute
  '/blocos/$blocoId': typeof BlocosBlocoIdRoute
  '/atividades': typeof AtividadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fontes': typeof FontesRoute
  '/sintese': typeof SinteseRoute
  '/atividades/$atividadeId': typeof AtividadesAtividadeIdRoute
  '/blocos/$blocoId': typeof BlocosBlocoIdRoute
  '/atividades/': typeof AtividadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fontes'
    | '/sintese'
    | '/atividades/$atividadeId'
    | '/blocos/$blocoId'
    | '/atividades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fontes'
    | '/sintese'
    | '/atividades/$atividadeId'
    | '/blocos/$blocoId'
    | '/atividades'
  id:
    | '__root__'
    | '/'
    | '/fontes'
    | '/sintese'
    | '/atividades/$atividadeId'
    | '/blocos/$blocoId'
    | '/atividades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FontesRoute: typeof FontesRoute
  SinteseRoute: typeof SinteseRoute
  AtividadesAtividadeIdRoute: typeof AtividadesAtividadeIdRoute
  BlocosBlocoIdRoute: typeof BlocosBlocoIdRoute
  AtividadesIndexRoute: typeof AtividadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sintese': {
      id: '/sintese'
      path: '/sintese'
      fullPath: '/sintese'
      preLoaderRoute: typeof SinteseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/': {
      id: '/atividades/'
      path: '/atividades'
      fullPath: '/atividades/'
      preLoaderRoute: typeof AtividadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/$atividadeId': {
      id: '/atividades/$atividadeId'
      path: '/atividades/$atividadeId'
      fullPath: '/atividades/$atividadeId'
      preLoaderRoute: typeof AtividadesAtividadeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocos/$blocoId': {
      id: '/blocos/$blocoId'
      path: '/blocos/$blocoId'
      fullPath: '/blocos/$blocoId'
      preLoaderRoute: typeof BlocosBlocoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FontesRoute: FontesRoute,
  SinteseRoute: SinteseRoute,
  AtividadesAtividadeIdRoute: AtividadesAtividadeIdRoute,
  BlocosBlocoIdRoute: BlocosBlocoIdRoute,
  AtividadesIndexRoute: AtividadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
